### ISSUE TITLE
[BUG] Margin directive needs styling

### ISSUE THREAD

**Issue by AakashGfude** [QuantEcon/quantecon-book-theme#20] opened 2020-10-01 23:16 UTC
Margin directive in `sphinx-book-theme` has the following style:

<img width="1321" alt="Screen Shot 2020-10-02 at 9 14 05 am" src="https://user-images.githubusercontent.com/6542997/94872322-a9c49800-048f-11eb-8634-5ca7747f8896.png">

`quantecon-book-theme` does not have any styling at the moment for this directive and the **same** css as `sphinx-book-theme`  is not transferable.

We also need to think about if we need this directive at all in our theme. And if needed, then the design of it.

cc: @mmcky @DrDrij

**Comment by mmcky** [comment] 2020-10-01 23:53
thanks @AakashGfude I think our theme should have support for all the `default` myst components in `sphinx-book-theme`. A reason in stage 2 to explore inheritance etc. 

I can imagine we may add these through the text with pointers and notes.

**Comment by mmcky** [comment] 2021-06-02 02:12
Closing as duplicate of #101

**Closed by mmcky** 2021-06-02 02:12 UTC
Labels: bug
